version: '3'
services:
  # ELK Stack
  elk-logstash:
    image: chatopera/elk-logstash:6.5.4
    restart: always
    volumes:
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "15001:4999"
      - "15002:5000"
      - "15003:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms256m"
    depends_on:
      - elk-es

  elk-kibana:
    image: chatopera/elk-kibana:6.5.4
    restart: always
    volumes:
      - ./elk/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "15005:5601"
    depends_on:
      - elk-es

  elk-es:
    image: chatopera/elk-es:6.5.4
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx4g"
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elk/elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./elk/elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./elk/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT1:-9200}:9200"
      - "${ES_PORT2:-9300}:9300"

  elk-head:
    image: "chatopera/elasticsearch-head:5_20200127"
    restart: always
    ports:
      - "${HEAD_PORT:-9100}:9100"
